### ISSUE TITLE
코드 리뷰 : 우준호 튜터

### ISSUE THREAD

**Issue by noggong** [kinnjoo/PROJECT_Blog_LV3#1]
코멘트가 많이 필요없을 정도로 잘 하셨습니다!
고생하셨습니다!

https://github.com/kinnjoo/PROJECT_Blog_LV3/blob/823a0254a8dec9af420f6009b25a91bd534ca115/routes/posts.js#L65
https://github.com/kinnjoo/PROJECT_Blog_LV3/blob/823a0254a8dec9af420f6009b25a91bd534ca115/routes/posts.js#L83
이미 해당 게시물의 사용자권한을 확인했다면 and 조건으로 userId 를 넣을 필요가 없어 보입니다.

---

https://github.com/kinnjoo/PROJECT_Blog_LV3/blob/823a0254a8dec9af420f6009b25a91bd534ca115/routes/users.js#L20
db 에서 사용자를 가져오는것은 다른 요청 데이터의 유효성 검사를 끝내고 하는것이 좋습니다.
db 에 요청하는것은 많은 리소스를 소모하는 행위인데 유효성 통과 못할때는 굳이 할필요가 없기 때문입니다.

----
https://github.com/kinnjoo/PROJECT_Blog_LV3/blob/823a0254a8dec9af420f6009b25a91bd534ca115/routes/users.js#L54
https://github.com/kinnjoo/PROJECT_Blog_LV3/blob/823a0254a8dec9af420f6009b25a91bd534ca115/middlewares/auth-middleware.js#L20
jwt secret key 는 따로 설정파일에 빼는게 좋으며 github 에 노출되면 안됩니다.

----
https://github.com/kinnjoo/PROJECT_Blog_LV3/blob/823a0254a8dec9af420f6009b25a91bd534ca115/middlewares/auth-middleware.js#L24
JWT 는 verify 를 하면서 해당 토큰이 문제 없다는것을 보장 합니다. 필요에 따라 사용자 정보를 미들웨어에서 가져오기도 하지만, 사용자의 아이디만 필요한 경우 없어도 될듯합니다.

**Comment by kinnjoo** [comment]
감사합니다! 남겨주신 코멘트를 토대로 과제 수정했습니다
